vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("chus.plugins-setup")
require("chus.core.options")
require("chus.core.keymaps")
require("chus.core.colorscheme")
require("chus.plugins.nvimtree")
require("lualine").setup()
require("chus.plugins.nvim-cmp")
require("chus.plugins.lsp.mason")
require("chus.plugins.lsp.lspsaga")
require("chus.plugins.lsp.lspconfig")
require("chus.plugins.lsp.null-ls")
require("chus.plugins.autopairs")
require("chus.plugins.treesitter")
require("chus.plugins.snippets.luasnip")
require("chus.plugins.blankline")
require("chus.plugins.comment")
require("chus.plugins.term")
require("chus.plugins.dap")
-- require("chus.plugins.hardtime")
require("chus.godot-config")
require("chus.plugins.ufo")
require("chus.plugins.tailwind")
